apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-spark-application-manager
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-airflow-worker-spark-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-airflow-worker
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-spark-application-manager
  apiGroup: rbac.authorization.k8s.io