apiVersion: v2
name: mci-data-platform
description: Plateforme data MCI (MinIO, Airflow, Kafka, NiFi, Trino)
version: 1.0.0

dependencies:
  - name: minio
    version: "5.4.0"
    repository: ""

  - name: trino
    version: "1.42.2"
    repository: ""

  - name: kafka
    version: "32.4.3"
    repository: ""

  - name: kafka-ui
    version: "0.7.6"
    repository: ""

  - name: nifi
    version: "1.2.1"
    repository: ""
