minio:
  persistence:
    size: 5Gi
  buckets:
    - name: raw-landing
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: lakehouse
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: archive
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: airflow-logs
      policy: none
      purge: false
      versioning: false
      objectlocking: false

airflow:
  images:
    airflow:
      repository: abraneb97/mci-airflow
      tag: "latest"
      pullPolicy: IfNotPresent 
  config:
    kubernetes_executor:
      delete_worker_pods: "True"
    core:
      dagbag_import_timeout: "120"

    logging:
      remote_logging: "True"
      remote_base_log_folder: "s3://airflow-logs/"
      remote_log_conn_id: "minio_s3_conn"

  dags:
    gitSync:
      enabled: true
      repo: https://github.com/AbrahamNebout/ArtefactChallenge.git
      branch: master
      rev: HEAD
      depth: 1
      maxFailures: 0
      subPath: "K8s/dag"
      credentialsSecret: git-credentials


spark-operator:
  sparkJobNamespaces:
    - default

  webhook:
    enable: true
  


dataGenerator:
  enabled: true

  image:
    repository: abraneb97/app-generator-k8s
    tag: "latest"         
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    nodePort: 30911

  resources: {}

trino: {}

iceberg:
  enabled: true
  warehouseBucket: lakehouse   # bucket déjà déclaré dans minio.buckets, cohérent
  postgres:
    user: iceberg
    password: iceberg          # à remplacer par un Secret externe en vrai contexte prod
    database: iceberg_catalog
    persistence:
      size: 2Gi


streamingJobs:
  enabled: true
  image: abraneb97/stream_image_k8s:v1
  rawToSilverJobs:
    - bank_transactions
    - insurance_operations
    - mobile_money
  silverToGoldJobs:
    - fraud_multiple_txn
    - fraud_unusual_country
    - fraud_claim_ratio
    - aml_threshold
    - liquidity_alerts

kafka:
  provisioning:
    enabled: true
    waitForKafka: true
    useHelmHooks: true
    numPartitions: 2
    replicationFactor: 1
    topics:
      - name: raw-bank-transactions
        partitions: 3
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: raw-insurance-operations
        partitions: 3
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: raw-mobile-money-payments
        partitions: 1
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: dlq-financial-events
        partitions: 3
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: gold-liquidity-alerts
        partitions: 1
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: raw-loan-repayments
        partitions: 3
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: gold-aml-events
        partitions: 1
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: silver-bank-transactions
        partitions: 1
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: silver-insurance-operations
        partitions: 3
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: gold-fraud-alerts
        partitions: 1
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

      - name: silver-mobile-money
        partitions: 1
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete

kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: yaml
          bootstrapServers: data-platform-kafka:9092

nifi: {}

kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password
    service:
      type: NodePort
      nodePort: 30909